name: Web deploy to IPFS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Clean latest build
        run: rm -rf dist

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Copy build to remote IPFS node
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.IPFS_SSH_HOST }}
          username: ${{ secrets.IPFS_SSH_USER }}
          key: ${{ secrets.IPFS_SSH_PRIVATE_KEY }}
          source: "dist"
          target: "/tmp/deploy"

      - name: Deploy via SSH and update CID to N1
        id: ipfs_add
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.IPFS_SSH_HOST }}:22
          username: ${{ secrets.IPFS_SSH_USER }}
          key: ${{ secrets.IPFS_SSH_PRIVATE_KEY }}
          script: |
            CID=$(ipfs-cluster-ctl add -Q -r --cid-version 1 --hidden /tmp/deploy/dist)
            echo "CID=$CID"
            rm -rf /tmp/deploy
            ipfs name publish --key=privx /ipfs/$CID
            sudo sed -i "s/\(proxy_set_header Host \).*\;/\1$CID.ipfs.localhost;/" /etc/nginx/sites-available/bridge.helpverse.ai.conf
            sudo systemctl reload nginx